<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIpaoe1o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIpaoe1o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIpaoe1o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIpaoe1o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIpaoe1o\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ipaoe1o',
    'container.build_id' => 'da5c1010',
    'container.build_time' => 1741298578,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIpaoe1o');
