<?php

namespace ContainerIpaoe1o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GfDkbejService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gfDkbej' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gfDkbej'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paiementRepository' => ['privates', '.errored.7XURxRv', NULL, 'Cannot determine controller argument for "App\\Controller\\PaiementController::listPaymentsByDebt()": the $paiementRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\PaiementRepository". Did you forget to add a use statement?'],
        ], [
            'paiementRepository' => '?',
        ]);
    }
}
