<?php

namespace ContainerIpaoe1o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WLsdr2nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WLsdr2n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WLsdr2n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepository' => ['privates', '.errored.McF1cix', NULL, 'Cannot determine controller argument for "App\\Controller\\ArticleController::listArticlesByName()": the $articleRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ArticleRepository". Did you forget to add a use statement?'],
        ], [
            'articleRepository' => '?',
        ]);
    }
}
