<?php

namespace ContainerIpaoe1o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Q0tlZscService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Q0tlZsc' shared service.
     *
     * @return \App\Controller\Dette
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\DetteController::showDebt()": the $dette argument is type-hinted with the non-existent class or interface: "App\\Controller\\Dette". Did you forget to add a use statement?');
    }
}
