<?php

namespace ContainerL1IO2gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Td4qIa8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Td4qIa8' shared service.
     *
     * @return \App\Controller\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\DetteController::filterDebts()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?');
    }
}
