<?php

namespace ContainerL1IO2gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F9oVB8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F9o_VB8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F9o_VB8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController::listArticles' => ['privates', '.service_locator.GIi9U7f', 'get_ServiceLocator_GIi9U7fService', true],
            'App\\Controller\\ArticleController::createArticle' => ['privates', '.service_locator.ZOhv0cf', 'get_ServiceLocator_ZOhv0cfService', true],
            'App\\Controller\\ArticleController::listArticlesByName' => ['privates', '.service_locator.WLsdr2n', 'get_ServiceLocator_WLsdr2nService', true],
            'App\\Controller\\ArticleController::listArticlesWithLowStock' => ['privates', '.service_locator.rVYfI1F', 'get_ServiceLocator_RVYfI1FService', true],
            'App\\Controller\\DetteController::listDebts' => ['privates', '.service_locator.5GLkrXo', 'get_ServiceLocator_5GLkrXoService', true],
            'App\\Controller\\DetteController::showDebt' => ['privates', '.service_locator.CAh4xWS', 'get_ServiceLocator_CAh4xWSService', true],
            'App\\Controller\\DetteController::createDebt' => ['privates', '.service_locator.YNwQXrZ', 'get_ServiceLocator_YNwQXrZService', true],
            'App\\Controller\\DetteController::listDebtsByClient' => ['privates', '.service_locator.5M7zgys', 'get_ServiceLocator_5M7zgysService', true],
            'App\\Controller\\DetteController::listDebtsByStatus' => ['privates', '.service_locator.TOWKzWs', 'get_ServiceLocator_TOWKzWsService', true],
            'App\\Controller\\DetteController::listDebtsByArticle' => ['privates', '.service_locator.KuIB6Gt', 'get_ServiceLocator_KuIB6GtService', true],
            'App\\Controller\\DetteController::filterDebts' => ['privates', '.service_locator..k4g1wz', 'get_ServiceLocator__K4g1wzService', true],
            'App\\Controller\\PaiementController::createPayment' => ['privates', '.service_locator.Z_HioGB', 'get_ServiceLocator_ZHioGBService', true],
            'App\\Controller\\PaiementController::listPaymentsByDebt' => ['privates', '.service_locator.gfDkbej', 'get_ServiceLocator_GfDkbejService', true],
            'App\\Controller\\PaiementController::listPaymentsByDate' => ['privates', '.service_locator.od3fie8', 'get_ServiceLocator_Od3fie8Service', true],
            'App\\Controller\\UtilisateurController::listUsersByRole' => ['privates', '.service_locator.Nz89Bbm', 'get_ServiceLocator_Nz89BbmService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController:listArticles' => ['privates', '.service_locator.GIi9U7f', 'get_ServiceLocator_GIi9U7fService', true],
            'App\\Controller\\ArticleController:createArticle' => ['privates', '.service_locator.ZOhv0cf', 'get_ServiceLocator_ZOhv0cfService', true],
            'App\\Controller\\ArticleController:listArticlesByName' => ['privates', '.service_locator.WLsdr2n', 'get_ServiceLocator_WLsdr2nService', true],
            'App\\Controller\\ArticleController:listArticlesWithLowStock' => ['privates', '.service_locator.rVYfI1F', 'get_ServiceLocator_RVYfI1FService', true],
            'App\\Controller\\DetteController:listDebts' => ['privates', '.service_locator.5GLkrXo', 'get_ServiceLocator_5GLkrXoService', true],
            'App\\Controller\\DetteController:showDebt' => ['privates', '.service_locator.CAh4xWS', 'get_ServiceLocator_CAh4xWSService', true],
            'App\\Controller\\DetteController:createDebt' => ['privates', '.service_locator.YNwQXrZ', 'get_ServiceLocator_YNwQXrZService', true],
            'App\\Controller\\DetteController:listDebtsByClient' => ['privates', '.service_locator.5M7zgys', 'get_ServiceLocator_5M7zgysService', true],
            'App\\Controller\\DetteController:listDebtsByStatus' => ['privates', '.service_locator.TOWKzWs', 'get_ServiceLocator_TOWKzWsService', true],
            'App\\Controller\\DetteController:listDebtsByArticle' => ['privates', '.service_locator.KuIB6Gt', 'get_ServiceLocator_KuIB6GtService', true],
            'App\\Controller\\DetteController:filterDebts' => ['privates', '.service_locator..k4g1wz', 'get_ServiceLocator__K4g1wzService', true],
            'App\\Controller\\PaiementController:createPayment' => ['privates', '.service_locator.Z_HioGB', 'get_ServiceLocator_ZHioGBService', true],
            'App\\Controller\\PaiementController:listPaymentsByDebt' => ['privates', '.service_locator.gfDkbej', 'get_ServiceLocator_GfDkbejService', true],
            'App\\Controller\\PaiementController:listPaymentsByDate' => ['privates', '.service_locator.od3fie8', 'get_ServiceLocator_Od3fie8Service', true],
            'App\\Controller\\UtilisateurController:listUsersByRole' => ['privates', '.service_locator.Nz89Bbm', 'get_ServiceLocator_Nz89BbmService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ArticleController::listArticles' => '?',
            'App\\Controller\\ArticleController::createArticle' => '?',
            'App\\Controller\\ArticleController::listArticlesByName' => '?',
            'App\\Controller\\ArticleController::listArticlesWithLowStock' => '?',
            'App\\Controller\\DetteController::listDebts' => '?',
            'App\\Controller\\DetteController::showDebt' => '?',
            'App\\Controller\\DetteController::createDebt' => '?',
            'App\\Controller\\DetteController::listDebtsByClient' => '?',
            'App\\Controller\\DetteController::listDebtsByStatus' => '?',
            'App\\Controller\\DetteController::listDebtsByArticle' => '?',
            'App\\Controller\\DetteController::filterDebts' => '?',
            'App\\Controller\\PaiementController::createPayment' => '?',
            'App\\Controller\\PaiementController::listPaymentsByDebt' => '?',
            'App\\Controller\\PaiementController::listPaymentsByDate' => '?',
            'App\\Controller\\UtilisateurController::listUsersByRole' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ArticleController:listArticles' => '?',
            'App\\Controller\\ArticleController:createArticle' => '?',
            'App\\Controller\\ArticleController:listArticlesByName' => '?',
            'App\\Controller\\ArticleController:listArticlesWithLowStock' => '?',
            'App\\Controller\\DetteController:listDebts' => '?',
            'App\\Controller\\DetteController:showDebt' => '?',
            'App\\Controller\\DetteController:createDebt' => '?',
            'App\\Controller\\DetteController:listDebtsByClient' => '?',
            'App\\Controller\\DetteController:listDebtsByStatus' => '?',
            'App\\Controller\\DetteController:listDebtsByArticle' => '?',
            'App\\Controller\\DetteController:filterDebts' => '?',
            'App\\Controller\\PaiementController:createPayment' => '?',
            'App\\Controller\\PaiementController:listPaymentsByDebt' => '?',
            'App\\Controller\\PaiementController:listPaymentsByDate' => '?',
            'App\\Controller\\UtilisateurController:listUsersByRole' => '?',
        ]);
    }
}
