<?php

namespace ContainerL1IO2gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CAh4xWSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CAh4xWS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CAh4xWS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dette' => ['privates', '.errored.Q0tlZsc', NULL, 'Cannot determine controller argument for "App\\Controller\\DetteController::showDebt()": the $dette argument is type-hinted with the non-existent class or interface: "App\\Controller\\Dette". Did you forget to add a use statement?'],
        ], [
            'dette' => '?',
        ]);
    }
}
