<?php

namespace ContainerL1IO2gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__K4g1wzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..k4g1wz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..k4g1wz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'request' => ['privates', '.errored.Td4qIa8', NULL, 'Cannot determine controller argument for "App\\Controller\\DetteController::filterDebts()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
            'detteRepository' => ['privates', '.errored.HKj2XTp', NULL, 'Cannot determine controller argument for "App\\Controller\\DetteController::filterDebts()": the $detteRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\DetteRepository". Did you forget to add a use statement?'],
        ], [
            'request' => '?',
            'detteRepository' => '?',
        ]);
    }
}
