<?php

namespace ContainerL1IO2gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_D85sLcvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.D85sLcv' shared service.
     *
     * @return \App\Controller\UtilisateurRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\UtilisateurController::listUsersByRole()": the $utilisateurRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\UtilisateurRepository". Did you forget to add a use statement?');
    }
}
